module.exports = {
   ...require('./listas/MantenimientoCtr'),
   ...require('./listas/IdentificacionCtr'),
   ...require('./listas/TipoCompraCtr'),
   ...require('./listas/TipoActivoCtr'),
   ...require('./listas/PisosCtr'),
   ...require('./listas/ModelosCtr'),
   ...require('./listas/PaisCtr'),
   ...require('./listas/TipoEstado'),
   ...require('./listas/ActivoCtr'),
   ...require('./listas/CiudadCtr'),
   ...require('./listas/ColoresCtr'),
   ...require('./listas/DisponibilidadCtr'),
   ...require('./listas/MarcasCtr'),
   ...require('./listas/MaterialesCtr'),
}