module.exports = {
    ...require('./TipoMantenimiento'),
    ...require('./TipoCompra'),
    ...require('./TipoActivo'),
    ...require('./TipoIdentificacion'),
    ...require('./Pisos'),
    ...require('./Modelos'),
    ...require('./Pais'),
    ...require('./TipoEstado'),
    ...require('./Marca'),
    ...require('./Activo'),
    ...require('./Ciudad'),
    ...require('./Colores'),
    ...require('./Disponibilidad'),
    ...require('./Materiales'),
    ...require('./UbicacionInventario'),
    ...require('./EmpleadosEmpresa'),
    ...require('./Inventario')
}